### ISSUE TITLE
[Doc request]

### ISSUE THREAD

**Issue by Kuzma30** [GS90/addFC#1]
Need more detailed documentation how to work with WB (not only examples).

**Comment by Pendelf** [comment]
I wanted to feel it too, but it's not clear how to use it

**Comment by GS90** [comment]
Documentation is in the process of being created and will appear soon.

**Comment by GS90** [comment]
Added the main part of the documentation.

**Comment by GS90** [comment]
@Kuzma30, @Pendelf
Completed the documentation.
Wrote it in as much detail as I could, hopefully it will be useful...
If there are no objections, I will close this issue.
