### ISSUE TITLE
How does sheetmetal batch processing work ?

### ISSUE THREAD

**Issue by luzpaz** [GS90/addFC#3]
Per https://github.com/GS90/addFC?tab=readme-ov-file#overview

cc @shaise

**Comment by GS90** [comment]
Hi, @luzpaz
If I understood the meaning of your question correctly...

This is a very simple implementation, briefly:

BOM generation reads the properties of all elements.
To define an element as a sheet metal part, 2 properties are required: "Name" and "Unfold".

Next, each part with `Unfold == True` is processed: a simple copy (reproduction) is created, a face with the largest area is found for it, this face is selected and `SMUnfoldUnattended` is applied. K-Factor for generating a "flat pattern" depends on the thickness and is specified in the preferences.

The sketch is saved to an external file (dxf or svg) in the selected directory, specified in the dialog box.

https://github.com/user-attachments/assets/f6c55880-821a-4f00-973e-f1d0bb351997

![smbp](https://github.com/user-attachments/assets/cff41583-4878-4044-b2ec-71379fc3b538)

![pref](https://github.com/user-attachments/assets/79377c8d-25a1-456a-a5c6-35a819df1db4)

[example.zip](https://github.com/user-attachments/files/17351569/example.zip)

**Comment by GS90** [comment]
Is this answer complete enough to consider the issue closed?
